language: java
install: true

os:
 - linux

cache:
  directories:
    - $HOME/.gradle

jdk:
 - oraclejdk8


before_script:
 - chmod +x gradlew
 - ls -lrth

script:
 - gradle assemble
 - gradle jacocoTestReport coveralls