language: java
install: true

cache:
  directories:
    - $HOME/.gradle

jdk:
 - oraclejdk8

before_install:
 - chmod +x gradlew
 - chmod 777 gradle
 - ls -lrth

after_success:
 - ./gradlew jacocoTestReport coveralls